cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@14'
brew 'redis'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'stripe/stripe-cli/stripe'
brew 'stripe/stripe-mock/stripe-mock'
brew 'wget'
brew 'yt-dlp'
brew 'watch'
